//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface PrinterPrx extends com.zeroc.Ice.ObjectPrx
{
    default byte[] playMusic(String s)
    {
        return playMusic(s, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default byte[] playMusic(String s, java.util.Map<String, String> context)
    {
        return _iceI_playMusicAsync(s, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<byte[]> playMusicAsync(String s)
    {
        return _iceI_playMusicAsync(s, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<byte[]> playMusicAsync(String s, java.util.Map<String, String> context)
    {
        return _iceI_playMusicAsync(s, context, false);
    }

    /**
     * @hidden
     * @param iceP_s -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<byte[]> _iceI_playMusicAsync(String iceP_s, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<byte[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "playMusic", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_s);
                 }, istr -> {
                     byte[] ret;
                     ret = istr.readByteSeq();
                     return ret;
                 });
        return f;
    }

    default String getSongList()
    {
        return getSongList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getSongList(java.util.Map<String, String> context)
    {
        return _iceI_getSongListAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSongListAsync()
    {
        return _iceI_getSongListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSongListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getSongListAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getSongListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSongList", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getSearchByTitle(String title)
    {
        return getSearchByTitle(title, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getSearchByTitle(String title, java.util.Map<String, String> context)
    {
        return _iceI_getSearchByTitleAsync(title, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSearchByTitleAsync(String title)
    {
        return _iceI_getSearchByTitleAsync(title, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSearchByTitleAsync(String title, java.util.Map<String, String> context)
    {
        return _iceI_getSearchByTitleAsync(title, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getSearchByTitleAsync(String iceP_title, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSearchByTitle", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getSearchByAuthor(String author)
    {
        return getSearchByAuthor(author, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getSearchByAuthor(String author, java.util.Map<String, String> context)
    {
        return _iceI_getSearchByAuthorAsync(author, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSearchByAuthorAsync(String author)
    {
        return _iceI_getSearchByAuthorAsync(author, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getSearchByAuthorAsync(String author, java.util.Map<String, String> context)
    {
        return _iceI_getSearchByAuthorAsync(author, context, false);
    }

    /**
     * @hidden
     * @param iceP_author -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getSearchByAuthorAsync(String iceP_author, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getSearchByAuthor", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_author);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void changeSongTitle(String title, String newTitle)
    {
        changeSongTitle(title, newTitle, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void changeSongTitle(String title, String newTitle, java.util.Map<String, String> context)
    {
        _iceI_changeSongTitleAsync(title, newTitle, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> changeSongTitleAsync(String title, String newTitle)
    {
        return _iceI_changeSongTitleAsync(title, newTitle, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> changeSongTitleAsync(String title, String newTitle, java.util.Map<String, String> context)
    {
        return _iceI_changeSongTitleAsync(title, newTitle, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_newTitle -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_changeSongTitleAsync(String iceP_title, String iceP_newTitle, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "changeSongTitle", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_newTitle);
                 }, null);
        return f;
    }

    default void changeSongAuthor(String title, String newAuthor)
    {
        changeSongAuthor(title, newAuthor, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void changeSongAuthor(String title, String newAuthor, java.util.Map<String, String> context)
    {
        _iceI_changeSongAuthorAsync(title, newAuthor, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> changeSongAuthorAsync(String title, String newAuthor)
    {
        return _iceI_changeSongAuthorAsync(title, newAuthor, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> changeSongAuthorAsync(String title, String newAuthor, java.util.Map<String, String> context)
    {
        return _iceI_changeSongAuthorAsync(title, newAuthor, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param iceP_newAuthor -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_changeSongAuthorAsync(String iceP_title, String iceP_newAuthor, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "changeSongAuthor", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                     ostr.writeString(iceP_newAuthor);
                 }, null);
        return f;
    }

    default void deleteSong(String title)
    {
        deleteSong(title, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void deleteSong(String title, java.util.Map<String, String> context)
    {
        _iceI_deleteSongAsync(title, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> deleteSongAsync(String title)
    {
        return _iceI_deleteSongAsync(title, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> deleteSongAsync(String title, java.util.Map<String, String> context)
    {
        return _iceI_deleteSongAsync(title, context, false);
    }

    /**
     * @hidden
     * @param iceP_title -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_deleteSongAsync(String iceP_title, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteSong", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_title);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PrinterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PrinterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PrinterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static PrinterPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static PrinterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static PrinterPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, PrinterPrx.class, _PrinterPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default PrinterPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (PrinterPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default PrinterPrx ice_adapterId(String newAdapterId)
    {
        return (PrinterPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default PrinterPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (PrinterPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default PrinterPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (PrinterPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default PrinterPrx ice_invocationTimeout(int newTimeout)
    {
        return (PrinterPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default PrinterPrx ice_connectionCached(boolean newCache)
    {
        return (PrinterPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default PrinterPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (PrinterPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PrinterPrx ice_secure(boolean b)
    {
        return (PrinterPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default PrinterPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (PrinterPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default PrinterPrx ice_preferSecure(boolean b)
    {
        return (PrinterPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default PrinterPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (PrinterPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default PrinterPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (PrinterPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default PrinterPrx ice_collocationOptimized(boolean b)
    {
        return (PrinterPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default PrinterPrx ice_twoway()
    {
        return (PrinterPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default PrinterPrx ice_oneway()
    {
        return (PrinterPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default PrinterPrx ice_batchOneway()
    {
        return (PrinterPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default PrinterPrx ice_datagram()
    {
        return (PrinterPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default PrinterPrx ice_batchDatagram()
    {
        return (PrinterPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default PrinterPrx ice_compress(boolean co)
    {
        return (PrinterPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default PrinterPrx ice_timeout(int t)
    {
        return (PrinterPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default PrinterPrx ice_connectionId(String connectionId)
    {
        return (PrinterPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default PrinterPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (PrinterPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Printer";
    }
}
